### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by hafedh-trimeche** [YuriSizuku/win-MemoryModule#11]
Hello,

Please note these error under Visual Studio 2022:

```
Error	C1083	Cannot open include file: 'stdio.h': No such file or directory	winmemdll_test	D:\DevStudio\win-MemoryModule\src\winmemdll_test.c	1		
Error	C1083	Cannot open include file: 'stdio.h': No such file or directory	winmemdll	D:\DevStudio\win-MemoryModule\src\winmemdll.c	6		
```
Would Delphi/Pascal wrapper be provided?

Best regards.

**Comment by YuriSizuku** [comment]
You might need to install  `msvc v141_xp` before compile if using visual studio. 
I will not provide `Delphi/Pascal` wrapper as I don't know this language. 
If you are familiar with this, you can make a contribute to this wrapper.

**Comment by YuriSizuku** [comment]
I will close this issue if no other comments.
